# -*- coding: utf-8 -*-
"""

User Configuration Setup Routine

This file creates a simple GUI for users to configure the main pipeline script.

To add more fields to the GUI simply add a help_text and add_basic_row line to the 
main GUI construction section, then add a par["eg"] statement to the
init_config and save_config functions. Extract any filepaths as you normally 
would to use elsewhere in the codebase.

"""

#%%     IMPORT MODULES

import tkinter as tk
from tkinter import ttk
from pathlib import Path
import config_managers as cfgm

#%%     ARCHITECTURE USER-INPUTS

# Use this section to customize the row entries for the config.ini and GUI

# Define config architecture (i.e. the config.ini sections and field variable names)
cfg_arch = {
    "PROJECT": ["WORK_DIR", "DOE_PROJ_DIR", "OF_CASE_DIR_TEMPLATE"],
    "CREO": ["CREO_MODEL_FP", "CREO_EXE_FP", "CREOSON_DIR"],
    "ANSYS": ["WB_PROJ_FP", "WB_EXE_FP"]
}

# Define field info for the GUI
field_info = {}

field_info["WORK_DIR"] = {
    "label": "Working Directory",
    "help_text": (
        "The working directory should be set to whatever directory this script "
        "is stored inside. Normally, this field is populated automatically by "
        "the script. However, if the script couldn't find the directory, you "
        "can always enter the working directory here instead."
    ),
    "is_file": False,
}
field_info["DOE_PROJ_DIR"] = {
    "label": "DOE Project Directory",
    "help_text": (
        "The directory where the script will store the parameter input sheet, "
        "mesh optimization sheet, VBA macros, and all generated variant meshes."
    ),
    "is_file": False,
}
field_info["OF_CASE_DIR_TEMPLATE"] = {
    "label": "OpenFOAM Case Directory Template",
    "help_text": (
        "The OpenFOAM case directory that will be copied and used for every "
        "geometry variant generated by the script. The directory should include "
        "everything necessary for your particular OpenFOAM case setup except "
        "the mesh file.\n\n"
        "(Note: This script assumes that case setup is otherwise identical for "
        "all generated variants.)"
    ),
    "is_file": False,
}
field_info["CREO_MODEL_FP"] = {
    "label": "Creo Parametric CAD Model File",
    "help_text": (
        "The filepath for the Creo Parametric CAD file. This is the CAD that "
        "the mesh will be generated from and then input into the simulations.\n\n"
        "(Note: This file should not include the part version. The script will "
        "automatically try to remove the version number but you can also just "
        "remove the numbered portion of the file extension yourself to be sure: "
        "e.g., my_part.prt.23 --> my_part.prt)"
    ),
    "is_file": True,
}
field_info["CREO_EXE_FP"] = {
    "label": "Creo Parametric Executable",
    "help_text": (
        "The filepath for the 'parametric.exe' file."
    ),
    "is_file": True,
}
field_info["CREOSON_DIR"] = {
    "label": "CreoSON Directory",
    "help_text": (
        "The CreoSON directory containing the CreoSON application and all "
        "supporting files.\n\n"
        "(e.g., C:\\Program Files\\CreosonServerWithSetup-3.0.1-win64)"
    ),
    "is_file": False,
}
field_info["WB_PROJ_FP"] = {
    "label": "Workbench Project Files",
    "help_text": (
        "Select one or more Workbench project files."
    ),
    "is_file": True,
    "dynamic": True,                                # Dynamic list field 
    "add_button_text": "Add another .wbpj file",    # Dynamic list button
}
field_info["WB_EXE_FP"] = {
    "label": "ANSYS Workbench Executable",
    "help_text": (
        "The filepath for the Workbench 'RunWB2.exe' file."
    ),
    "is_file": True,
}

#%%     CONFIG INITIALIZATION

# Try to find correct working directory
try:
    # If running outside IDE, try to get working directory from script location
    SCRIPT_FP = Path(__file__).resolve()
    WORK_DIR = SCRIPT_FP.parent
except:
    # If running inside IDE, try to assign current working directory from default
    WORK_DIR = Path.cwd().resolve()
    SCRIPT_FP = WORK_DIR / "setup_config.py"
if not Path(SCRIPT_FP).exists():
    print("WARNING: Could not determine the script location. Please set WORK_DIR variable manually.")

# Try to find config.ini file
config_path = Path("config.ini").resolve()
app = cfgm.ConfigSetupApp(config_path=config_path, arch=cfg_arch)

# Load config.ini file it if it exists, otherwise run initializiation routine
if config_path.exists():
    app.config.read(config_path)
else:
    app.init_config(WORK_DIR)
    
#%%     GUI WINDOW CONSTRUCTION

# Construct main window object that will display the GUI
gui = cfgm.GUIBootstrap(GUIwidth=875, GUIheight=600, title="DOE CFD Automation - Setup Configuration", global_font="Segoe UI")

# Initialize row index for the main GUI window
main_row = 0

# Create a short instructional label at top of GUI
ltxt = ("Populate the fields below with the absolute filepaths for your "
        "CFD setup (manually or using the browser dialogs).")
label = ttk.Label(gui.scrollwin, text=ltxt, font=("Segoe UI", 10))
label.grid(row=main_row, column=0, columnspan=5, pady=20, sticky="")

main_row += 1

#%%     GUI ROW ENTRY CONSTRUCTION

# Initialize dynamic entries dictionary
dynamic_entries = {}

# Loop through every section and field variable defined within config architecture
for section, field_vars in cfg_arch.items():
    for var in field_vars:
        # Extract field variable info dictionary
        info = field_info[var]

        # Make a dynamic entry list row if the field variable is set to dynamic
        if bool(info.get("dynamic")):

            # Define a frame just for this field variable's dynamic entry rows
            dyn_frame = ttk.Frame(gui.scrollwin)
            dyn_frame.grid(row=main_row, column=0, columnspan=5, sticky="w")
            
            # Construct the initial template entry row for the dynamic list
            row_obj = cfgm.EntryRow(
                window=dyn_frame,
                window_row_ind=0,
                row_label=info["label"],
                help_text=info["help_text"],
                config_value=""
            )
            
            # Initialize add button object to pass into the DynamicRowList object
            add_btn = ttk.Button(dyn_frame, text=info.get("add_button_text", "Add Another"))

            # Construct the dynamic row entry list
            row_list = cfgm.DynamicRowList(
                frame=dyn_frame,
                row_template=row_obj,
                add_button=add_btn,
                is_file=info["is_file"],
                conditional=True
            )

            # Construct the add button for the dynamic list
            add_btn.config(command=row_list.append_row_list)
            row_list.append_row_list()
            
            # Save any new entries created by the user to the dynamic entries dict
            dynamic_entries[var] = row_list.entries
            
            main_row += 1
        
        # For a normal entry list row, just create one row
        else:
            # Extract row values from the config.ini
            value = app.config_get(section, var)

            # Create the entry row and insert values from the config.ini if they exist
            row_obj = cfgm.EntryRow(
                window=gui.scrollwin, 
                window_row_ind=main_row, 
                row_label=info["label"],
                help_text=info["help_text"],
                config_value=value)
            main_row = row_obj.add_basic_row(app.entries, is_file=info["is_file"])

# Construct the config save button within the GUI
save_btn = cfgm.SaveButton(window=gui.scrollwin, config_app=app)
save_btn.place_save_btn(window_row=main_row, window_col=2)

# Create a short explanatory label for executables at bottom of GUI window
ltxt = (
    "Note: For executables, the filepath should be for the actual executable "
    "file, not the shortcut often used to launch the software from Desktop. "
    "If you don't know where to find the real executable, go to the shortcut "
    "and right-click > Properties > Target will reveal the absolute filepath "
    "to input here. Additionally, you must ensure that this is the correct "
    "version of the software you want to run if you have multiple versions "
    "installed on your PC."
)
label = ttk.Label(gui.scrollwin, text=ltxt, justify="left", font=("Arial", 8), wraplength=gui.width-50)
label.grid(row=main_row+1, column=0, columnspan=5)

# Display the GUI
gui.mainwin.mainloop()
