# -*- coding: utf-8 -*-
"""

User Configuration Setup Routine

This file creates a simple GUI for users to configure the main pipeline script.

To add more fields to the GUI simply add a help_text and add_basic_row line to the 
main GUI construction section, then add a par["eg"] statement to the
init_config and save_config functions. Extract any filepaths as you normally 
would to use elsewhere in the codebase.

"""

#%%     IMPORT MODULES

import tkinter as tk
from tkinter import ttk
from pathlib import Path
import config_managers as cfgm
import json

#%%     ARCHITECTURE USER-INPUTS

# Use this section to customize the row entries for the config.ini and GUI

# Define config architecture (i.e. the config.ini sections and field variable names)
cfg_arch = {
    "PROJECT": ["WORK_DIR", "DOE_PROJ_DIR", "OF_CASE_DIR_TEMPLATE"],
    "CREO": ["CREO_MODEL_FP", "CREO_EXE_FP", "CREOSON_DIR"],
    "ANSYS": ["WB_PROJ_FP", "WB_EXE_FP"]
}

# Define field info for the GUI
field_info = {}

field_info["WORK_DIR"] = {
    "label": "Working Directory",
    "help_text": (
        "The working directory should be set to whatever directory this script "
        "is stored inside. Normally, this field is populated automatically by "
        "the script. However, if the script couldn't find the directory, you "
        "can always enter the working directory here instead."
    ),
    "mode": "folder",
}
field_info["DOE_PROJ_DIR"] = {
    "label": "DOE Project Directory",
    "help_text": (
        "The directory where the script will store the parameter input sheet, "
        "mesh optimization sheet, VBA macros, and all generated variant meshes."
    ),
    "mode": "folder",
}
field_info["OF_CASE_DIR_TEMPLATE"] = {
    "label": "OpenFOAM Case Directory Template",
    "help_text": (
        "The OpenFOAM case directory that will be copied and used for every "
        "geometry variant generated by the script. The directory should include "
        "everything necessary for your particular OpenFOAM case setup except "
        "the mesh file.\n\n"
        "(Note: This script assumes that case setup is otherwise identical for "
        "all generated variants.)"
    ),
    "mode": "folder",
}
field_info["CREO_MODEL_FP"] = {
    "label": "Creo Parametric CAD Model File",
    "help_text": (
        "The filepath for the Creo Parametric CAD file. This is the CAD that "
        "the mesh will be generated from and then input into the simulations.\n\n"
        "(Note: This file should not include the part version. The script will "
        "automatically try to remove the version number but you can also just "
        "remove the numbered portion of the file extension yourself to be sure: "
        "e.g., my_part.prt.23 --> my_part.prt)"
    ),
    "mode": "file",
}
field_info["CREO_EXE_FP"] = {
    "label": "Creo Parametric Executable",
    "help_text": (
        "The filepath for the 'parametric.exe' file."
    ),
    "mode": "file",
}
field_info["CREOSON_DIR"] = {
    "label": "CreoSON Directory",
    "help_text": (
        "The CreoSON directory containing the CreoSON application and all "
        "supporting files.\n\n"
        "(e.g., C:\\Program Files\\CreosonServerWithSetup-3.0.1-win64)"
    ),
    "mode": "folder",
}
field_info["WB_PROJ_FP"] = {
    "label": "Workbench Project Files",
    "help_text": (
        "The filepath for the ANSYS Workbench \".wbpj\" project file(s) that "
        "will be used to mesh the CAD geometry. \n\nIf there are any features "
        "in the CAD geometry that you only want activated or suppressed under "
        "certain conditions, then you can add another \".wbpj\" file "
        "and associate it with parameter range(s) so that the script can "
        "alter the geometry using Creo|SON and then automatically mesh using the "
        " alternate \".wbpj\" file."
    ),
    "mode": "file",
    "dynamic": True,                                # Dynamic list field 
    "add_button_text": "Add another .wbpj file",    # Dynamic list button
}
field_info["WB_EXE_FP"] = {
    "label": "ANSYS Workbench Executable",
    "help_text": (
        "The filepath for the Workbench 'RunWB2.exe' file."
    ),
    "mode": "file",
}

#%%     CONFIG INITIALIZATION

# Try to find correct working directory
try:
    # If running outside IDE, try to get working directory from script location
    SCRIPT_FP = Path(__file__).resolve()
    WORK_DIR = SCRIPT_FP.parent
except:
    # If running inside IDE, try to assign current working directory from default
    WORK_DIR = Path.cwd().resolve()
    SCRIPT_FP = WORK_DIR / "setup_config.py"
if not Path(SCRIPT_FP).exists():
    print("WARNING: Could not determine the script location. Please set WORK_DIR variable manually.")

# Try to find config.json file
config_path = Path("config.json").resolve()

# Instantiate config setup app object
app = cfgm.ConfigSetupApp(config_path=config_path, arch=cfg_arch)

# Load config.json file it if it exists, otherwise run initializiation routine
if not config_path.exists():
    app.init_config(work_dir=WORK_DIR)
    
#%%     GUI WINDOW CONSTRUCTION

# Construct main window object that will display the GUI
gui = cfgm.GUIBootstrap(GUIwidth=1000, GUIheight=600, title="DOE CFD Automation - Setup Configuration", global_font="Segoe UI")

# Initialize row index for the main GUI window
main_row = 0

# Create a short instructional label at top of GUI
ltxt = ("Populate the fields below with the absolute filepaths for your "
        "CFD setup (manually or using the browser dialogs).")
label = ttk.Label(gui.scroll_frame, text=ltxt, font=("Segoe UI", 10))
label.grid(row=main_row, column=0, columnspan=5, pady=20, sticky="")

# Increment main window row index
main_row += 1

#%%     GUI ENTRY ROW CONSTRUCTION

# Loop through every section and field variable defined within config architecture
for section, field_vars in cfg_arch.items():
    for var in field_vars:
        
        # Extract field variable info dictionary
        info = field_info[var]

        # ---------- DYNAMIC ENTRY ROW ---------
        if bool(info.get("dynamic")):

            # Load previously saved dynamic values from config.ini
            saved_values = app.config_get(section, var)

            dyn_entry_one = cfgm.EntryRow(
                container=gui.scroll_frame,
                field_var=var,
                row_ind=main_row,
                norm_label_kwargs={
                    "widget": {"text": info["label"]}
                },
                tooltip_label_kwargs={
                    "hover_label": {"text": info["help_text"]}
                }
            )
                                   

            # Create the DynamicRowList object
            app.dynamic_entries[var] = cfgm.DynamicRowList(
                dyn_entry_one,
                show_label=False,
                browse_mode=info["mode"],
                conditional=True,
                config_values=saved_values,
                add_btn_wg_kwargs = {"text": info.get("add_button_text", "Add Another")}
            )

            # Increment main window row index (main entry + dynamic list frame)
            main_row += 2
        # ---------------------------------------
        # ----------- NORMAL ENTRY ROW ----------
        else:
            # Extract row value from the config.json
            value = app.config_get(section, var)

            # Instantiate entry row object and store config entry value if it exists
            row_obj = cfgm.EntryRow(
                container=gui.scroll_frame,
                field_var=var,
                row_ind=main_row,
                norm_label_kwargs={
                    "widget": {"text": info["label"]}
                },
                tooltip_label_kwargs={
                    "hover_label": {"text": info["help_text"]}
                }
            )

            # Construct filepath entry row
            app.entries_dict[var] = row_obj.build_fp_row(info["mode"])
                
            # Increment main window row index
            main_row += 1
        # ---------------------------------------
        
# --- Load config AFTER all widgets are created ---
if config_path.exists():
    app.load_config()

#%%     MISC. GUI WIDGETS

# Construct the config save button within the GUI
save_btn = cfgm.SaveButton(container=gui.scroll_frame, config_app_obj=app, btn_grid_kwargs={"column": 2})
save_btn.build_save_btn()

# Construct an explanatory label for executables at bottom of GUI
ltxt = (
    "Note: For executables, the filepath should be for the actual executable "
    "file, not the shortcut often used to launch the software from Desktop. "
    "If you don't know where to find the real executable, go to the shortcut "
    "and right-click > Properties > Target will reveal the absolute filepath "
    "to input here. Additionally, you must ensure that this is the correct "
    "version of the software you want to run if you have multiple versions "
    "installed on your PC."
)
label = ttk.Label(gui.scroll_frame, text=ltxt, justify="left", font=("Arial", 8), wraplength=gui.width-50)
label.grid(row=main_row+1, column=0, columnspan=5)

#%%     GUI RUNTIME

# Display the GUI
gui.window.mainloop()
