# -*- coding: utf-8 -*-
"""
Created on Fri Jun 19 12:20:44 2026

@author: Sean
"""

#%%     IMOPRT MODULES

# Standard modules
from dataclasses import dataclass, field
from typing import List

# Custom modules
from config_io import ConfigSetupApp
import inputrow_blueprints as irBP
from inputrow_builders import InputRow, InputRowBuilder

#%%     POLY INPUT ROW SPECIFICATION DATACLASSES

@dataclass
class BasePolyInputRowSpec:
    """
    Baseline specification dataclass for every type of poly input row. 
    """
    
    parent_row_obj: InputRow
    specs: List[irBP.BaseInputRowSpec]
    cfg_app_obj: ConfigSetupApp
        
    # Map all available row builder methods to their respective spec type
    IR_BUILDERS = {
        irBP.FilepathInputRowSpec: InputRowBuilder.build_fp_inputrow,
        irBP.ConditionInputRowSpec: InputRowBuilder.build_cond_inputrow,
    }
    
    def __post_init__(self):
        """ 
        Post-construction method for all poly input row builders. 
        """
        
        # I. EXTRACTION: get widget/grid kwarg dicts, default to empty dicts
        # Extract parent row context
        self.p_container = self.parent_row_obj.ctx.container
        self.p_row_ind = self.parent_row_obj.ctx.row_ind
        self.p_base_col_ind = self.parent_row_obj.ctx.base_col_ind
        self.p_cfg_group = self.parent_row_obj.ctx.cfg_group
        self.p_cfg_field = self.parent_row_obj.ctx.cfg_field
        self.p_cfg_rowid = self.parent_row_obj.ctx.cfg_rowid
        
    def _validate_grids(self, grid_list):
        """
        Ensures no grid kwargs contain forbidden spatial keys.
        """
    
        forbidden = {"row", "column"}
    
        for grid in grid_list:
            spatial = set(grid) & forbidden
    
            if spatial:
                raise ValueError(
                    f"{self.__class__.__name__} grid kwargs must not contain {forbidden}. "
                    "Spatial positioning is controlled by the builder."
                )

@dataclass
class DynamicPolyInputRowSpec(BasePolyInputRowSpec):
    """
    Specification dataclass for dynamic input row builders.
    """
    
    # Force any mutable defaults to be created for every instance of the class 
    dyn_frame_kwargs: dict = field(default_factory=dict)
    btn_frame_kwargs: dict = field(default_factory=dict)
    add_btn_kwargs: dict = field(default_factory=dict)
        
    def __post_init__(self):
        """ 
        Post-construction method for dynamic input row builders. 
        """ 
        
        # Inherit/call the BasePolyInputRowSpec post-construction method
        super().__post_init__()
        
        # Extract add button keyword arguments (force identical buttons for each spectype)
        self.dyn_frame_wg_kwargs = self.dyn_frame_kwargs.get("widget", {})
        self.dyn_frame_grid_kwargs = self.dyn_frame_kwargs.get("grid", {})
        self.btn_frame_wg_kwargs = self.btn_frame_kwargs.get("widget", {})
        self.btn_frame_grid_kwargs = self.btn_frame_kwargs.get("grid", {})
        self.add_btn_wg_kwargs = self.add_btn_kwargs.get("widget", {})
        self.add_btn_grid_kwargs = self.add_btn_kwargs.get("grid", {})
        
        # II. DEFAULTS: assign default keyword arguments
        # Set default widget options for button frame widget
        self.add_btn_wg_kwargs.setdefault("style", "AddRow.TButton")
        self.add_btn_wg_kwargs.setdefault("style", "AddRow.TButton")
        
        # Set default grid options for button frame widget
        self.btn_frame_grid_kwargs.setdefault("sticky", "ew")
        self.btn_frame_grid_kwargs["columnspan"] = 999  # Force buttons to span all input row columns
        
        # Set default grid options for "add input row" button widget
        self.add_btn_grid_kwargs.setdefault("pady", 5)
        self.add_btn_grid_kwargs.setdefault("padx", 10)
        
        # III. CLEANUP: remove/override some keyword arguments or throw error
        # Validate grids
        grid_list = [
            self.add_btn_grid_kwargs
        ]
        self._validate_grids(grid_list)
        
        # Validate widget kwargs
        if self.add_btn_wg_kwargs.get("text"):
            raise ValueError(
                f"{self.__class__.__name__} widget kwargs cannot contain text. "
                "Add button text is automatically generated by InputRowSpec type."
            )